apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg-statefulset
  labels:
    app: database
spec:
  replicas: 5
  selector:
    matchLabels:
      app: database
  serviceName: "database"
  template:
    metadata:
      labels:
        app: database
    spec:
      imagePullSecrets:
        - name: auth-master3-registry
      containers:
        - name: database
          image: registry.master3.takima.io/guide/kubernetes-resources/db:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-data
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: pg-config
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: username
            - name: PGDATA
              valueFrom:
                configMapKeyRef:
                  name: pg-config # Nom du configmap
                  key: DB_PATH # nom de la clef dans le configMap contenant path ou installer la db dans le volume persistant
  volumeClaimTemplates:
  - metadata:
      name: pg-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

